Pin `safety` package version to less than `2.0.0`
Lucas-C/pre-commit-hooks-safety pull request #30
Opened 2022-06-29 07:06 UTC by sshishov

This is `hotfix` to support old `safety` package

2022-06-29 10:14 UTC, Kurt-von-Laven requested changes
Greatly appreciate the fixes @sshishov!

2022-06-30 06:51 UTC, sshishov commented on setup.py
> +        'safety<2.0.0',
Thanks @Kurt-von-Laven , going to add the minimum pinned version as `1.0.0`. Do not want to do a hard pin as the mentioned product can still have some small bug fixes and patch versions.

2022-06-30 06:58 UTC, sshishov commented on setup.py
> +        'safety<2.0.0',
Updated, thanks

2022-06-30 08:00 UTC, Kurt-von-Laven approved these changes
That seems perfectly reasonable. Thank you for putting up these fixes so quickly! They seem solid to me and very low-risk to merge considering the hook is presently dead in the water. I think the safest thing would be to merge this one first, do a release, and then merge the other one and do another release.

2022-06-30 09:00 UTC, sshishov commented
@Kurt-von-Laven This fix is much more safe than another. I will add the note in another MR regarding my concerns

2022-07-01 13:55 UTC, Lucas-C commented
Thank you for the PR!

Sadly this wasn't passing the GitHub Actions checks.

It has been superseded by [release v1.3.0](https://github.com/Lucas-C/pre-commit-hooks-safety/releases/tag/v1.3.0)

Closing this now.

2022-07-01 13:55 UTC, closed without merging